import { action } from 'typesafe-actions';

export const DASHBOARD_GET_USERS = 'DASHBOARD_GET_USERS';
export const DASHBOARD_GET_USERS_SUCCESS = 'DASHBOARD_GET_USERS_SUCCESS';
export const DASHBOARD_GET_USERS_ERROR = 'DASHBOARD_GET_USERS_ERROR';

export const DASHBOARD_GET_POSTS = 'DASHBOARD_GET_POSTS';
export const DASHBOARD_GET_POSTS_SUCCESS = 'DASHBOARD_GET_POSTS_SUCCESS';
export const DASHBOARD_GET_POSTS_ERROR = 'DASHBOARD_GET_POSTS_ERROR';

export const DASHBOARD_GET_ALBUMS = 'DASHBOARD_GET_ALBUMS';
export const DASHBOARD_GET_ALBUMS_SUCCESS = 'DASHBOARD_GET_ALBUMS_SUCCESS';
export const DASHBOARD_GET_ALBUMS_ERROR = 'DASHBOARD_GET_ALBUMS_ERROR';

export const DASHBOARD_GET_PHOTOS = 'DASHBOARD_GET_PHOTOS';
export const DASHBOARD_GET_PHOTOS_SUCCESS = 'DASHBOARD_GET_PHOTOS_SUCCESS';
export const DASHBOARD_GET_PHOTOS_ERROR = 'DASHBOARD_GET_PHOTOS_ERROR';

export const DASHBOARD_GET_DATA = 'DASHBOARD_GET_DATA';
export const DASHBOARD_GET_DATA_SUCCESS = 'DASHBOARD_GET_DATA_SUCCESS';
export const DASHBOARD_GET_DATA_ERROR = 'DASHBOARD_GET_DATA_ERROR';

export const dashboardGetUsers = () => action(DASHBOARD_GET_USERS);
export const dashboardGetPosts= () => action(DASHBOARD_GET_POSTS);
export const dashboardGetAlbums = () => action(DASHBOARD_GET_ALBUMS);
export const dashboardGetPhotos = () => action(DASHBOARD_GET_PHOTOS);

export const dashboardGetData = () => action(DASHBOARD_GET_DATA);

